apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundryVtt.fullname" . }}
  labels:
    app: {{ template "foundryVtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  adminKey: {{ default "admin" .Values.foundryConfig.adminKey | b64enc }}
  {{- if .Values.foundryConfig.username }}
  username: {{ .Values.foundryConfig.username | b64enc }}
  {{- end }}
  {{- if .Values.foundryConfig.password }}
  password: {{ .Values.foundryConfig.password | b64enc }}
  {{- end }}
  {{- if .Values.foundryConfig.license_key }}
  license_key: {{ .Values.foundryConfig.license_key | b64enc }}
  {{- end }}
---
{{- if .Values.selfsigned }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundryVtt.fullname" . }}-signed
  labels:
    app: {{ template "foundryVtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  tls.crt: {{ .Values.selfsigned.cert | b64enc }}
  tls.key: {{ .Values.selfsigned.key | b64enc }}
type: kubernetes.io/tls
{{- end }}

---
{{- if eq .Values.foundryConfig.s3.awsConfig "file" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundryVtt.fullname" . }}-aws
  labels:
    app: {{ template "foundryVtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  aws-credentials.json: {{ printf "{\"accessKeyId\": \"%s\", \"secretAccessKey\": \"%s\", \"region\": \"%s\" }" .Values.foundryConfig.s3.aws_access_key_id .Values.foundryConfig.s3.aws_secret_access_key .Values.foundryConfig.s3.aws_region | b64enc }}
{{- end }}

---
{{- if .Values.foundryConfig.turnConfigs -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "foundryVtt.fullname" . }}-turn-configs
  labels:
    app: {{ template "foundryVtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  turnConfigs.json: {{ toJson .Values.foundryConfig.turnConfigs | b64enc }}
{{- end }}